pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r src/* public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
  environment:
    name: Development
    url: https://neurchi.gitlab.io/bfmemes

production:
  stage: deploy
  image: python:3.7
  before_script:
    - pip install paramiko
  script:
    - python deploy.py
  only:
   - prod
  environment:
    name: Production
    url: https://bfmemes.com