pages:
  stage: deploy
  script:
    - mkdir website
    - cp -r src/* website
  artifacts:
    paths:
      - website
    expire_in: 1 week
  only:
    - master
  environment:
    name: Development
    url: https://neurchi.gitlab.io/bfmemes

deploy to production:
  stage: deploy
  image: debian:9.8
  before_script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y openssh-client sshpass
  script:
    - bash deploy.sh
  only:
   - prod
  environment:
    name: Production
    url: https://bfmemes.com