pages:
  stage: deploy
  image: node:14
  script:
    - yarn install
    - yarn build --url=https://neurchi.gitlab.io/bfmemes
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
  environment:
    name: Development
    url: https://neurchi.gitlab.io/bfmemes

production:
  stage: deploy
  image: node:14
  before_script:
    - apt update
    - apt install python3 python3-pip
    - pip3 install paramiko
  script:
    - yarn install
    - yarn build
    - python3 deploy.py
  only:
   - prod
  environment:
    name: Production
    url: https://generator.bfmemes.com